# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import showtime_pb2 as showtime__pb2


class ShowtimeStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetScheduleByDate = channel.unary_unary(
        '/Showtime/GetScheduleByDate',
        request_serializer=showtime__pb2.ScheduleDate.SerializeToString,
        response_deserializer=showtime__pb2.Schedule.FromString,
        )
    self.GetAllSchedules = channel.unary_stream(
        '/Showtime/GetAllSchedules',
        request_serializer=showtime__pb2.EmptySchedule.SerializeToString,
        response_deserializer=showtime__pb2.Schedules.FromString,
        )


class ShowtimeServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetScheduleByDate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAllSchedules(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ShowtimeServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetScheduleByDate': grpc.unary_unary_rpc_method_handler(
          servicer.GetScheduleByDate,
          request_deserializer=showtime__pb2.ScheduleDate.FromString,
          response_serializer=showtime__pb2.Schedule.SerializeToString,
      ),
      'GetAllSchedules': grpc.unary_stream_rpc_method_handler(
          servicer.GetAllSchedules,
          request_deserializer=showtime__pb2.EmptySchedule.FromString,
          response_serializer=showtime__pb2.Schedules.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Showtime', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
