# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import booking_pb2 as booking__pb2


class BookingStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetAllBookings = channel.unary_stream(
        '/Booking/GetAllBookings',
        request_serializer=booking__pb2.EmptyBooking.SerializeToString,
        response_deserializer=booking__pb2.BookingData.FromString,
        )
    self.GetBookingByUser = channel.unary_unary(
        '/Booking/GetBookingByUser',
        request_serializer=booking__pb2.UserID.SerializeToString,
        response_deserializer=booking__pb2.BookingData.FromString,
        )
    self.PostBookingByUser = channel.unary_unary(
        '/Booking/PostBookingByUser',
        request_serializer=booking__pb2.NewBooking.SerializeToString,
        response_deserializer=booking__pb2.BookingData.FromString,
        )


class BookingServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetAllBookings(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBookingByUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PostBookingByUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BookingServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetAllBookings': grpc.unary_stream_rpc_method_handler(
          servicer.GetAllBookings,
          request_deserializer=booking__pb2.EmptyBooking.FromString,
          response_serializer=booking__pb2.BookingData.SerializeToString,
      ),
      'GetBookingByUser': grpc.unary_unary_rpc_method_handler(
          servicer.GetBookingByUser,
          request_deserializer=booking__pb2.UserID.FromString,
          response_serializer=booking__pb2.BookingData.SerializeToString,
      ),
      'PostBookingByUser': grpc.unary_unary_rpc_method_handler(
          servicer.PostBookingByUser,
          request_deserializer=booking__pb2.NewBooking.FromString,
          response_serializer=booking__pb2.BookingData.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Booking', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
